version: '3.4'

services:
  clinica:
    image: ${DOCKER_REGISTRY-}clinica
    build:
      context: .
      dockerfile: clinica/Dockerfile
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "1nf3rn0#@"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - '11433:1433'    
    expose:
      - 1433 
  
      
       
       